// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ8q-J0Kb8VmgyLYdBf1lpM8wFQlNmVgw',
    appId: '1:482945289076:android:77d1b635b4ad693a2bfa21',
    messagingSenderId: '482945289076',
    projectId: 'selise-95b34',
    storageBucket: 'selise-95b34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD7leNjQHS1CLWd2-OoKNtpqQfnBwz5Ac',
    appId: '1:482945289076:ios:2fd24a8d22076d592bfa21',
    messagingSenderId: '482945289076',
    projectId: 'selise-95b34',
    storageBucket: 'selise-95b34.appspot.com',
    androidClientId: '482945289076-5ms5k8bd5qd96ktfor9bv8q56t8rp0sn.apps.googleusercontent.com',
    iosClientId: '482945289076-fnubs50mmtklra9itpo9pvb8h721ivab.apps.googleusercontent.com',
    iosBundleId: 'com.example.seliseAssignment',
  );
}
